In [1]:
import numpy as np

x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [2]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: user 6.8 ms, sys: 0 ns, total: 6.8 ms
Wall time: 6.49 ms


In [3]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [4]:
%%time
z = x + y

CPU times: user 40 µs, sys: 38 µs, total: 78 µs
Wall time: 86.5 µs


In [5]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [7]:
a == b

array([False,  True, False,  True])

In [8]:
a >= b

array([False,  True,  True,  True])

In [9]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [10]:
np.all(a == b)

False

In [11]:
np.all(a == c)

True

In [12]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [13]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [14]:
10 ** a

array([    1,    10,   100,  1000, 10000])

In [15]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [18]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [23]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [24]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [25]:
x + y

array([1, 2, 3, 4, 5])

In [26]:
x + 1

array([1, 2, 3, 4, 5])

In [27]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [28]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [29]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [31]:
y = np.arange(3)
y

array([0, 1, 2])

In [32]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [33]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [34]:
np.sum(x)

10

In [35]:
x.sum()

10

In [38]:
x = np.array([1,3,2])
x

array([1, 3, 2])

In [39]:
x.min()

1

In [40]:
x.max()

3

In [41]:
x.argmin()

0

In [42]:
x.argmax()

1

In [44]:
x = np.array([1,2,3,1])
x

array([1, 2, 3, 1])

In [45]:
x.mean()

1.75

In [46]:
np.median(x)

1.5

In [47]:
np.all([True, True, False])

False

In [49]:
np.any([True, True, False])

True

In [50]:
a = np.zeros((100,100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:
np.any(a != 0)

False

In [52]:
np.all(a == a)

True

In [53]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

In [54]:
((a <= b) & (b <= c)).all()

True

In [55]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [56]:
x.sum()

6

In [57]:
x.sum(axis=0)

array([3, 3])

In [58]:
x.sum(axis=1)

array([2, 4])

In [71]:
exam_arr = np.vstack([range(11)[i:i + 5] for i in range(6)])
print(exam_arr)
print(exam_arr.sum(axis=0))
print(exam_arr.max(axis=0))
print(exam_arr.mean(axis=1))
print(exam_arr.min(axis=1))

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]
[15 21 27 33 39]
[5 6 7 8 9]
[2. 3. 4. 5. 6. 7.]
[0 1 2 3 4 5]


In [72]:
a = np.array([[4,3,5,7],
            [1,12,11,9],
            [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [73]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [74]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [76]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [77]:
a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [78]:
a[j]

array([12, 25, 38, 42])

In [79]:
np.sort(a)

array([12, 25, 38, 42])

In [80]:
exam_arr = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
idx_arr = np.argsort(exam_arr[2])
idx_arr

array([1, 0, 2, 3])

In [83]:
print(exam_arr[0][idx_arr])
print(exam_arr[1][idx_arr])
print(exam_arr[2][idx_arr])

[2 1 3 4]
[ 99  46 100  71]
[ 59  81  90 100]
