In [1]:
import numpy as np

ar = np.array([0,1,2,3,4,5,6,7,8,9])

type(ar)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
data = [0,1,2,3,4,5,6,7,8,9]

answer = []

for di in data:
    answer.append(2*di)

data
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [3]:
x = np.array(data)
x
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
a = np.array([1,2,3])
b = np.array([10,20,30])

2*a+b

array([12, 24, 36])

In [5]:
2 == a
10 < b
(2 == a) & (10 < b)

array([False,  True, False])

In [6]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
len(c)
len(c[0])

3

In [8]:
ex_1_arr = np.array([[10,20,30,40],[50,60,70,80]])
ex_1_arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [9]:
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
d
len(d)
len(d[0])
len(d[0][0])

4

In [10]:
a.ndim
a.shape

(3,)

In [11]:
c.ndim
c.shape

(2, 3)

In [12]:
d.ndim
d.shape

(2, 3, 4)

In [13]:
a = np.array([0,1,2,3,4])
a[2]
a[-1]

a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
a[0,0]
a[0,1]
a[-1,-1]

5

In [15]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
a[0,:]
a[:,1]

array([1, 5])

In [17]:
a[1, 1:]
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [18]:
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

m[1][2]
m[2][4]
m[1,1:3]
m[1:,2]
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [19]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]#0,2,4,6,8

array([0, 2, 4, 6, 8])

In [20]:
a%2
a%2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [21]:
a[a%2 == 0]

array([0, 2, 4, 6, 8])

In [22]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [23]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [26]:
a[[2, 0, 1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [35]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
ex_1 = x[x%3 == 0]
print(ex_1)
ex_2 = x[x%4 == 1]
print(ex_2)
ex_3 = ex_1 == ex_2
print(ex_3)

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
