In [1]:
import numpy as np

np.random.seed(0)

In [2]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [3]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [4]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.random.shuffle(x)
x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

In [6]:
np.random.choice(5, 5, replace=False)

array([0, 4, 2, 1, 3])

In [11]:
np.random.choice(5, 3, replace=False)

array([2, 0, 3])

In [20]:
np.random.choice(5, 10)

array([0, 3, 2, 3, 0, 4, 0, 0, 2, 3])

In [26]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([0, 3, 2, 3, 3, 3, 2, 0, 3, 2])

In [27]:
np.random.randn(10)

array([-0.59432737, -0.10569679,  0.74279571, -0.75498153, -0.13828271,
       -2.12492027, -1.03001883, -0.51745186, -0.14180001, -1.27648021])

In [28]:
np.random.randn(3, 5)

array([[ 1.48151328e+00,  1.65927664e+00,  1.39611962e-04,
         1.50583836e+00,  1.04520923e-01],
       [-2.36043151e-01,  8.19435034e-01,  4.02856439e-01,
        -1.43824188e+00,  2.71248834e-01],
       [-6.90603124e-01, -6.81532976e-01, -1.51223065e+00,
         2.19689103e+00,  1.04117502e+00]])

In [29]:
np.random.randint(10, size=10)

array([3, 1, 9, 5, 9, 9, 2, 0, 9, 1])

In [30]:
np.random.randint(10, 20, size=10)

array([19, 10, 16, 10, 14, 18, 14, 13, 13, 18])

In [31]:
np.random.randint(10, 20, size=(3, 5))

array([[18, 17, 10, 13, 18],
       [17, 17, 11, 18, 14],
       [17, 10, 14, 19, 10]])

In [32]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [33]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts=True)

In [34]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [35]:
count

array([2, 2, 1])

In [36]:
np.bincount([1,1,2,2,2,3], minlength=6)

array([0, 2, 3, 1, 0, 0])